CREATE OR REPLACE FUNCTION FindMinZeroBit (
  int_bit int8
) RETURNS
  int4
IMMUTABLE
RETURNS NULL ON NULL INPUT
PARALLEL SAFE
AS $$
DECLARE
  ONE_BIT CONSTANT int8 := 1;
  ZERO_BIT CONSTANT int8 := 0;
BEGIN
  FOR i IN 0..63 LOOP
    IF ((int_bit >> i) & ONE_BIT) = ZERO_BIT THEN
      RETURN i;
    END IF;
  END LOOP;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
